---
bases:
  - ../../bases/helmDefaults.yaml
  - ../../bases/environments.yaml

---
releases:
  - name: triton-client
    chart: ../../charts/raw
    installed: {{ .Values | getOrNil "triton-client.installed" | default false }}
    namespace: seldon-system
    createNamespace: true
    labels:
      tier: client
    values:
      - values.yaml.gotmpl
